
SET(CPACK_GENERATOR "STGZ;DEB")

SET(CPACK_PACKAGE_NAME "hackide")
SET(CPACK_PACKAGE_VENDOR "Damien 'bl0b' Leroux")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A nice and lightweight tmux wrapper to create persistent working environments that fit in a terminal.")
SET(CPACK_PACKAGE_CONTACT "Damien 'bl0b' Leroux <damien.leroux@gmail.com>")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "${PROJECT_SOURCE_DIR}/README.md")
SET(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/COPYING")
SET(CPACK_PACKAGE_FILE_NAME ${HACKIDE_NAME}-${CMAKE_VERSION_MAJOR}.${CMAKE_VERSION_MINOR}.${CMAKE_VERSION_PATCH})
SET(CPACK_PACKAGE_VERSION_MAJOR "${CMAKE_VERSION_MAJOR}")
SET(CPACK_PACKAGE_VERSION_MINOR "${CMAKE_VERSION_MINOR}")



SET(CPACK_DEBIAN_PACKAGE_NAME ${HACKIDE_NAME}-${CMAKE_VERSION_MAJOR}.${CMAKE_VERSION_MINOR})
SET(CPACK_DEBIAN_PACKAGE_VERSION ${CMAKE_VERSION_MAJOR}.${CMAKE_VERSION_MINOR})
SET(CPACK_DEBIAN_PACKAGE_DEPENDS "python, tmux")
SET(CPACK_DEBIAN_PACKAGE_BUILDS_DEPENDS "")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER ${CPACK_PACKAGE_CONTACT})
SET(CPACK_DEBIAN_PACKAGE_DESCRIPTION ${CPACK_PACKAGE_DESCRIPTION_SUMMARY})
#SET(CPACK_DEBIAN_PACKAGE_SECTION "")
SET(CPACK_DEBIAN_PACKAGE_PRIORITY "extra")

INCLUDE(CPack)
